In [4]:
import numpy as np


## Vector vector multiplication (dot product)

In [12]:
np.random.seed(42)

u = np.arange(5)
v = np.random.randint(0, 10, 5)

print(u)
print(v)

[0 1 2 3 4]
[6 3 7 4 6]


In [14]:
def vector_vector_mul(x, y):
    assert x.shape[0] == y.shape[0]
    
    result = 0.0
    for i in range(x.shape[0]):
        result += x[i] * y[i]
        
    return result

In [15]:
vector_vector_mul(u, v)

53.0

In [16]:
u.dot(v)

53

## Matrix vector multiplication (dot product)

In [17]:
np.random.seed(42)

U = np.random.randint(0, 10, (3,5))
U

array([[6, 3, 7, 4, 6],
       [9, 2, 6, 7, 4],
       [3, 7, 7, 2, 5]])

In [18]:
def matrix_vector_mul(X, y):
    assert X.shape[1] == y.shape[0]
    
    n_rows = X.shape[0]
    result = np.empty(n_rows)
    
    for i in range(n_rows):
        result[i] = vector_vector_mul(X[i], y)
    
    return result

In [19]:
matrix_vector_mul(U, v)

array([146., 154., 126.])

In [20]:
U.dot(v)

array([146, 154, 126])

## Matrix-matrix multiplication

In [22]:
np.random.seed(42)
V = np.random.randint(0, 10, (5,3))
V

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

In [23]:
def matrix_matrix_mul(X, Y):
    assert X.shape[1] == Y.shape[0]
    
    n_rows = X.shape[0]
    n_cols = Y.shape[1]
    result = np.empty((n_rows, n_cols))
    for i in range(n_cols):
        result[:, i] = matrix_vector_mul(X, Y[:, i])
        
    return result

In [24]:
matrix_matrix_mul(U, V)

array([[120., 102., 176.],
       [130., 104., 192.],
       [103., 109., 172.]])

In [25]:
U.dot(V)

array([[120, 102, 176],
       [130, 104, 192],
       [103, 109, 172]])

## Identity matrix

In [26]:
I_3 = np.eye(3)
I_3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.random.seed(42)
U = np.random.randint(0, 10, (3, 3))
U

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7]])

In [28]:
U.dot(I_3)

array([[6., 3., 7.],
       [4., 6., 9.],
       [2., 6., 7.]])

In [29]:
I_3.dot(U)

array([[6., 3., 7.],
       [4., 6., 9.],
       [2., 6., 7.]])

## Inverse matrix

In [30]:
U_inv = np.linalg.inv(U)
U_inv

array([[ 0.66666667, -1.16666667,  0.83333333],
       [ 0.55555556, -1.55555556,  1.44444444],
       [-0.66666667,  1.66666667, -1.33333333]])

In [31]:
U.dot(U_inv)

array([[ 1.00000000e+00,  0.00000000e+00,  8.88178420e-16],
       [ 5.55111512e-16,  1.00000000e+00,  2.66453526e-15],
       [ 3.33066907e-16, -1.77635684e-15,  1.00000000e+00]])

In [32]:
U_inv.dot(U)

array([[ 1.00000000e+00,  2.44249065e-15,  3.44169138e-15],
       [-4.44089210e-16,  1.00000000e+00,  2.22044605e-16],
       [ 0.00000000e+00, -8.88178420e-16,  1.00000000e+00]])