In [1]:
import numpy as np

## One-dimensional arrays

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
np.full(5, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5])

In [5]:
l = [1, 2, 3, 4, 5]

a = np.array(l)
a

array([1, 2, 3, 4, 5])

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [9]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multidimensional arrays

In [10]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
np.full((3,2), 2.5)

array([[2.5, 2.5],
       [2.5, 2.5],
       [2.5, 2.5]])

In [16]:
l = [
    [1, 2],
    [3, 4],
    [5, 6]
]

a = np.array(l)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
a[1,1]

4

In [18]:
a[2]

array([5, 6])

In [19]:
a[:, 0]

array([1, 3, 5])

In [20]:
a[2,0] = -5
a

array([[ 1,  2],
       [ 3,  4],
       [-5,  6]])

In [21]:
a[1] = [-1, -2]
a

array([[ 1,  2],
       [-1, -2],
       [-5,  6]])

In [22]:
a[:,0] = [1, 3, 5]

In [23]:
a

array([[ 1,  2],
       [ 3, -2],
       [ 5,  6]])

## Randomly generated arrays

In [24]:
np.random.seed(20)

In [25]:
np.random.rand(3,2)

array([[0.5881308 , 0.89771373],
       [0.89153073, 0.81583748],
       [0.03588959, 0.69175758]])

In [26]:
100 * np.random.rand(3,2)

array([[37.8680942 , 51.85109454],
       [65.79514656, 19.38502179],
       [27.23164021, 71.86059336]])

In [27]:
np.random.randn(3,2)

array([[ 0.50309684,  0.40641447],
       [ 0.32346101, -0.49341088],
       [-0.79201679, -0.84236793]])

In [30]:
np.random.randint(0,100,(3,2))

array([[75, 61],
       [77, 83],
       [57, 94]])

## Element wise operations

In [31]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [32]:
a + 1

array([1, 2, 3, 4, 5])

In [38]:
b = np.random.randint(0, 10, 5)
b

array([1, 8, 0, 2, 7])

In [35]:
a + b

array([110, 107, 177, 121, 107])

In [37]:
c = a**2
c

array([ 0,  1,  4,  9, 16])

In [39]:
a > b

array([False, False,  True,  True, False])

In [40]:
a[a>b]

array([2, 3])

## Summarization operations

In [41]:
a

array([0, 1, 2, 3, 4])

In [42]:
a.min()

0

In [43]:
a.max()

4

In [44]:
a.sum()

10

In [45]:
a.mean()

2.0

In [46]:
a.std()

1.4142135623730951

In [47]:
a.cumsum()

array([ 0,  1,  3,  6, 10])